### ISSUE TITLE
replace names.csv.gz and taxa.csv.gz with UTF-8 and unix-line endings

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/hesperomys#2]
Hi @JelleZijlstra  -

Thanks again for creating the names.csv.gz and taxa.csv.gz exports. 

As I was attempting to integrate hesperomys with Nomer to facilitate name alignments with MDD etc,

I noticed that grep didn't like the names.csv.gz . 

On closer inspection, I noticed that windows line endings and non-UTF-8 encoding, causing grep to be all confused:

```
cat names.csv.gz | gunzip | grep "Chiroptera"
```

produced no matches, and following stderr:

```
grep: (standard input): binary file matches
```

Any chance I can convince you to re-export the resources using unix line ending ("\n", not "\r\n") in UTF-8 encoding?

**Comment by JelleZijlstra** [comment]
I'll take a look. I think there were some weird characters (\x02 or something) and I had to use a non-standard `csv` option to get Python to write the CSV. I should probably have gotten rid of those characters instead.

Relatedly, I started thinking about how to publish these files in the future when I do releases for Hesperomys. My current plan is to generate a `.zip` file containing the two csvs and put it on Zenodo, with a link from hesperomys.com. Does that sound reasonable to you?

**Comment by jhpoelen** [comment]
@JelleZijlstra publishing sounds good to me. 

If possible, I'd prefer separate uncompressed csv / tsv files instead of a zip archive.

This way, folks can directly stream data from Zenodo, and most likely, the Zenodo web service will compress the content on the fly using some content negotiation.

**Comment by jhpoelen** [comment]
@JelleZijlstra thanks for sharing the new files via #3 . 

I was able to run - 

```
cat names.csv.gz | gunzip | grep "Chiroptera" | wc -l
```

without any complaints from grep. Results turns out to be:

```
6411
```

Lots of records mentioning Chiroptera.

**Comment by JelleZijlstra** [comment]
Good to hear! Yes, there are a lot of bats.
